### ISSUE TITLE
Basic usage example

### ISSUE THREAD

**Issue by lknite** [IvanJosipovic/KubernetesCRDModelGen#164]
I've got a few existing CRDs in kubernetes.  I'd like to be able to list those out, or find by name, and then pass one of them to KubernetesCRDModelGen in order to get class representation in C# that I can then use to create an instance of the CRD.

This project can do that yes?

If so, can you give an example of how to list out the CRDs initially in order to get one to pass to KubernetesCRDModelGen?

I've tried this but it wants to know what the CRD will be before I can loop through them:
```
// list out crds, looking for the specified crd
var generic = new GenericClient(Globals.service.kubeclient, "apiextensions.k8s.io", "v1", "customresourcedefinitions");

var crs = await generic.ListAsync<KubernetesObject>().ConfigureAwait(false);
foreach (var cr in crs.Items)
```

**Comment by lknite** [comment]
oh wait, i think i may have found it ...
```
            var crs = Globals.service.kubeclient.ListCustomResourceDefinition();
            foreach (var cr in crs.Items)
            {

            }
```

**Comment by IvanJosipovic** [comment]
Hey,

Here is how to use the GenericClient with Lists:

```
var client = new Kubernetes(KubernetesClientConfiguration.BuildDefaultConfig());

var gen = new GenericClient(client, V1CustomResourceDefinition.KubeGroup, V1CustomResourceDefinition.KubeApiVersion, V1CustomResourceDefinition.KubePluralName);

var crds = await gen.ListAsync<V1CustomResourceDefinitionList>();
```

**Comment by lknite** [comment]
And once we have a crd, how do we create an instance of the crd if we aren't able to create a class before hand?  This seems to be what this library does yes?  How to use it?

```
                    // Use GenericClient to locate crd
                    //

                    // KubernetesCRDModelGen
                    CRDGenerator gen = new CRDGenerator();
                    var o = await gen.GenerateAssembly(crd);
                    Console.WriteLine("crd:");
                    Console.WriteLine(o.ToString());

                    var myCr = o.Item1.CreateInstance("");
                    myCr.Metadata.Name = "name-of-new-crd-instance";
```

**Comment by IvanJosipovic** [comment]
Its rather complex to use it this, its doable and I do do that in my KubeUI project, https://github.com/IvanJosipovic/KubeUI/blob/alpha/src/KubeUI.Core/Client/ClusterBase.cs

If you are dealing with a static set of CRDs, you can create a empty project and put the yamls in it and use the SourceGenerator from this project.

See this folder, https://github.com/IvanJosipovic/KubernetesCRDModelGen/tree/alpha/src/Models/KubernetesCRDModelGen.Models.argoproj.io

The csproj inherits from this file, in your case, you would load the references from NuGet instead of files.
https://github.com/IvanJosipovic/KubernetesCRDModelGen/blob/alpha/src/Models/Directory.Build.props

**Comment by lknite** [comment]
Thank you
